package companyValueGui;

public class Descriptions {

	final static String croic = "Over the Long term, a company will generally grow at the rate at which it can generate owner earnings or cash based on the capital invested in the business"
			+ ".  In the short term, growth can happen at any speed.  Over th years, companies grow based on their CROIC - their cash return on invested capital."
			+ ". . . CROIC, expressed as a percentage, tells us how efficiently a business' operations and management can invest and reinvest capital into the business to"
			+ "generate even more cash . . . When trying to predict future cash flows, you will likely find the most success when using CROIC as a predictor of the future."
			+ "  If a business is generating 14% CROIC, you shouldn't expect it to grow much faster unless you have rational reason to believe it can."
			+ "  . . . In the case of Apple, a whole new business (the \"i\" business. . .) emerged . . .and past CROIC was useless as an indicator. "
			+ "- Add reference\n\n CROIC = FCF (cash return) / Long-Term Debt + Shareholder's Equity (Invested Capital).";

	final static String fcfGrowth = "If this number seems implausible it may not be trustworthy.  Swings from negative to positive fcf growth from year over year can cause strange"
			+ "results.  Check against fcf growth numbers from Yahoo Finance, etc.\n\nTo see the actual “earnings” for the business, and ultimately for the owner of XYZ Company (that is, the “owner earnings” as Buffett calls them), "
			+ "we start at the top—Cash Flows from Operating Activities, or the amount of cash generated by the day-to-day operations of the business.\n"
			+ "Owner Earnings = Net Income + Depreciation and Amortization + Non-Cash Charges – Average Capital Expenditures\nor\n"
			+ "Free Cash Flow = Cash Flow From Operations - Capital Expenditures"
			+ "Ponzio, Joel. F Wall Street: Joe Ponzio's No-Nonsense Approach to Value Investing For the Rest of Us (p. 83). Adams Media. Kindle Edition. "
			+ "Ponzio, Joel. F Wall Street: Joe Ponzio's No-Nonsense Approach to Value Investing For the Rest of Us (p. 76). Adams Media. Kindle Edition. ";

	final static String autoUpdate10k = "Auto Update: If data is manually entered this should remain disabled.  Enabling this may cause you to "
			+ "have to enter the data again or may cause the program to crash.  This governs continuous updates of price and market capitalization"
			+ "and the updating of the annual reports.\n"
			+ "This is when the data from the program was announced by the company.  Public companies must report this once a year.  The program"
			+ "checks automatically for updates to this report if auto update is toggled.";

}
